baseURL = 'https://fivetwentythree.github.io/personal-blog/'
canonifyURLs = true
languageCode = 'en-us'
title = 'Lochana Perera'
theme = 'etch'
disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = false
  xhtml = true

[markup.highlight]
  noClasses = false
  pygmentsUseClasses = true

[params]
  description = "peronal-blog"
  dark = "off"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true





